[mod]
id = "BuilderPlus"
name = "BuilderPlus"
version = "0.5.0"
description = "KSP-style vehicle builder interface for Kitten Space Agency"
authors = ["brunog___"]
license = "MIT"


[credits]
"PixelCode Font" = "qwerasd205 (https://github.com/qwerasd205/PixelCode)"

[dependencies]
starmap = ">=0.4.5"